export const GET_RECIPES = "GET_RECIPES";
export const GET_DIETS = "GET_DIETS";
export const GET_RECIPES_BY_NAME = "GET_RECIPES_BY_NAME";
export const NEXT_PAGE = "NEXT_PAGE";
export const PREV_PAGE = "PREV_PAGE";
export const CHANGE_PAG = "CHANGE_PAG";
export const SEARCH = "SEARCH";
export const CREATE_RECIPE = "CREATE_RECIPE";
export const DELETE_RECIPE = "DELETE_RECIPE";
export const FILTER_BY_DIETS = "FILTER_BY_DIETS";
export const FILTER_RECIPES_SOURCE = "FILTER_RECIPES_SOURCE";
export const FILTER_SORT_NAME = "FILTER_BY_DIETS";
export const FILTER_HEALTHSCORE = "FILTER_HEALTHSCORE";


